### ISSUE TITLE
Possibility to configure elapsed time 

### ISSUE THREAD

**Issue by alejandrodevs** [georapbox/canvas-circular-countdown#21]
Hi everyone,

I have a situation where a circular counter is shown to explain the user the time he has to complete a form. If the user suubmit the form and there are some server validation errors, the page is re render and I would like to start the circular countdown again but with the elapsed time instead of creating a countdown with less duration.

As far as I see in the code, there is an easy way to add it as configuration and pass it to the Timer class instead to always assign `this._time` with `0`. What do you think? Would you accept a PR with that?

**Comment by georapbox** [comment]
Hi @alejandrodevs ,

I would be more than happy to accept such a PR. Feel free to contribute!

Thanks

**Comment by alejandrodevs** [comment]
@georapbox Thank you, I created this PR #23

**Comment by georapbox** [comment]
It has been resolved in [v1.6.1](https://www.npmjs.com/package/canvas-circular-countdown/v/1.6.1).
Thanks for the contribution 😃
