### ISSUE TITLE
How to control the direction

### ISSUE THREAD

**Issue by zhongning7924** [georapbox/canvas-circular-countdown#29]
How to control the direction, clockwise

**Comment by georapbox** [comment]
Hi @zhongning7924 ,

Please see the attached video, is this what you're looking for? If so, it is not supported right now but I could add a `clockwise` option to support it pretty easily.


https://user-images.githubusercontent.com/6596039/198204128-f4d17640-b226-48f3-8e72-cb7bc7d04013.mov

**Comment by zhongning7924** [comment]
yeah that's what i want，looking forward to the release.

**Comment by zhongning7924** [comment]
> yeah that's what i want，looking forward to the release.

**Comment by georapbox** [comment]
It should be available by now as of v1.8.0. There is a new `clockwise` option (`false` by default) that controls the direction.
