### ISSUE TITLE
Display remaining time 

### ISSUE THREAD

**Issue by jpgateaux** [georapbox/canvas-circular-countdown#33]
is it possible to display remaining time instead of percentage?

**Comment by jpgateaux** [comment]
Newer mind after digging I foumd the answer.  Better documentation in order;

**Comment by georapbox** [comment]
I think what you're looking for is [Example 5](https://github.com/georapbox/canvas-circular-countdown#example-5---change-caption-text-depending-on-percentage) where you can update the `captionText` while the timer is running. If you use the `captionText` as function, the second argument passed is an object representing the remaining/elapsed time.

This is documented for `captionText` option in the <sup>1</sup> note:

> If it is a function, the remaining percentage and an object containing the remaining and elapsed time are passed as parameters and it should return the appropriate type for each option. For example, for showCaption should return a boolean (true or false), but for captionColor should return a string. Useful when you need to change some options' values depending on the remaining percentage or the remaining/elapsed time.

**Comment by jpgateaux** [comment]
Sorry what I was trying to do was replace percentage caption with time remaining .  Here is what I came up with:
`"captionText":function (percentage, time) {
	return Math.ceil(time.remaining/1000).toFixed();
}`

**Comment by georapbox** [comment]
Yep, this is pretty much the way to use it.
